---
title: "Ames house price"
author: "Choi won pyo"
date: '2021 3 18 '
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
```


```{r}
train <- read_csv("/cloud/project/train.csv")
test <- read_csv("/cloud/project/test.csv")
```


```{r}
ggplot(train, aes(x=OverallQual, y=SalePrice)) +
  geom_point()
```



```{r}
ggplot(train, aes(x =Neighborhood, y = SalePrice)) +
  geom_boxplot()
```




```{r}
Select <-train %>% group_by(Neighborhood) %>% 
  summarize(SalePrice_mean = mean(SalePrice)) %>% arrange(desc(SalePrice_mean))
```


```{r}
install.packages("MASS")
library(MASS)
```


```{r}
model.null <- lm(SalePrice ~ 1, train)
summary(model.null)
```


```{r}
model.full <- lm(SalePrice ~ Neighborhood + Condition1 + Condition2 + BldgType +
                   HouseStyle + OverallQual + OverallCond + YearBuilt + YearRemodAdd + RoofStyle +
                    RoofMatl + Exterior1st + Exterior2nd + MasVnrType + MasVnrArea + ExterQual +
                   ExterCond + Foundation + BsmtQual + BsmtCond + BsmtExposure + BsmtFinType1 +
                   BsmtFinSF1 + BsmtFinType2 + BsmtFinSF2 + BsmtUnfSF + TotalBsmtSF + Heating + HeatingQC +
                 BsmtFullBath + BsmtHalfBath + FullBath + HalfBath + BedroomAbvGr +
                   KitchenAbvGr + KitchenQual+ GarageType + GarageYrBlt + GarageFinish +
                  GarageCars + GarageArea + GarageQual + GarageCond , train)

summary(model.full)
```



```{r}
model.forward <- stepAIC(model.null, direction = "forward",
                         scope = list(upper = model.full,
                                      lower = model.null))
```


```{r}
model.forward1 <- lm(SalePrice ~ OverallQual + Neighborhood + TotalBsmtSF + HouseStyle + 
                        RoofMatl + KitchenQual + BldgType + BsmtFinSF1 , train) 

summary(model.forward1)
```


```{r}
ans1 <-predict(model.forward1, newdata = test)
ans1

ans2 <- data.frame(ans1)
View(ans2)
```











